[alias]
wasm = "build --release --target wasm32-unknown-unknown"
unit-test = "test --workspace"
schema = "run --bin schema"

[build]
rustflags = ["-C", "link-arg=-s"]

[env]
RUSTFLAGS = "-C link-arg=-s"